if ('undefined' === typeof HTTP) {
    var HTTP = require('http');
};
if ('undefined' === typeof URL) {
    var URL = require('url');
};
if ('undefined' === typeof PORT) {
    var PORT = 3000;
};
if ('undefined' === typeof VISITORCOUNT) {
    var VISITORCOUNT = 0;
};
function sendHtml(res, html) {
    res.statusCode = 200;
    res['content-type'] = 'text/html';
    __PS_MV_REG = [];
    return res.end(html);
};
function sendJson(res, jsonString) {
    res.statusCode = 200;
    res['content-type'] = 'application/json';
    __PS_MV_REG = [];
    return res.end(jsonString);
};
function substituteTemplate(template, placeholder, value) {
    return template.replace(placeholder, value);
};
function sendError(res, status, message) {
    res.statusCode = status;
    res['content-type'] = 'text/plain';
    __PS_MV_REG = [];
    return res.end(message);
};
function handleRoot(req, res) {
    VISITORCOUNT += 1;
    var html = '<!DOCTYPE html>' + '<html><head><meta charset=\"utf-8\"><title>Dynamic Server</title>' + '<style>body{font-family:Arial,sans-serif;margin:40px;background:#f0f8ff;}' + '.container{max-width:800px;margin:0 auto;background:white;padding:30px;border-radius:15px;box-shadow:0 4px 15px rgba(0,0,0,0.1);}' + '.route{background:#e8f4fd;padding:15px;margin:10px 0;border-radius:8px;border-left:5px solid #3498db;}' + 'a{color:#3498db;text-decoration:none;font-weight:bold;}' + 'a:hover{text-decoration:underline;}' + '</style></head><body>' + '<div class=\'container\'>' + '<h1>🚀 Dynamic Parenscript Server with Djula Templates</h1>' + '<p>Visitor count: ' + VISITORCOUNT + '</p>' + '<h2>Dynamic Routes:</h2>' + '<div class=\'route\'><a href=\'/user/alice\'>👤 /user/alice</a> - User profile</div>' + '<div class=\'route\'><a href=\'/user/bob\'>👤 /user/bob</a> - Another user</div>' + '<div class=\'route\'><a href=\'/post/123\'>📝 /post/123</a> - Blog post</div>' + '<div class=\'route\'><a href=\'/post/456\'>📝 /post/456</a> - Another post</div>' + '<div class=\'route\'><a href=\'/api/stats\'>📊 /api/stats</a> - Server statistics</div>' + '</div></body></html>';
    __PS_MV_REG = [];
    return sendHtml(res, html);
};
function handleUser(req, res, username) {
    var html = '<!DOCTYPE html>' + '<html><head><meta charset=\"utf-8\"><title>User: ' + username + '</title>' + '<style>body{font-family:Arial,sans-serif;margin:40px;background:#f0f8ff;}' + '.container{max-width:600px;margin:0 auto;background:white;padding:30px;border-radius:15px;box-shadow:0 4px 15px rgba(0,0,0,0.1);}' + '.avatar{width:80px;height:80px;border-radius:50%;background:#3498db;color:white;display:flex;align-items:center;justify-content:center;font-size:32px;margin:0 auto 20px;}' + 'a{color:#3498db;text-decoration:none;font-weight:bold;}' + '</style></head><body>' + '<div class=\'container\'>' + '<div class=\'avatar\'>' + username[0] + '</div>' + '<h1>👤 User Profile: ' + username + '</h1>' + '<p>Welcome, ' + username + '!</p>' + '<p>This is a dynamic route generated by Parenscript with Djula templating.</p>' + '<a href=\'/\'>← Back to Home</a>' + '</div></body></html>';
    __PS_MV_REG = [];
    return sendHtml(res, html);
};
function handlePost(req, res, postId) {
    var html = '<!DOCTYPE html>' + '<html><head><meta charset=\"utf-8\"><title>Post #' + postId + '</title>' + '<style>body{font-family:Arial,sans-serif;margin:40px;background:#f0f8ff;}' + '.container{max-width:800px;margin:0 auto;background:white;padding:30px;border-radius:15px;box-shadow:0 4px 15px rgba(0,0,0,0.1);}' + 'a{color:#3498db;text-decoration:none;font-weight:bold;}' + '</style></head><body>' + '<div class=\'container\'>' + '<h1>📝 Blog Post #' + postId + '</h1>' + '<p>This is post number ' + postId + '.</p>' + '<p>Generated dynamically by Parenscript with Djula templating!</p>' + '<h3>Technical Details:</h3>' + '<ul><li>Route: <code>/post/' + postId + '</code></li>' + '<li>Generated by: Parenscript from Common Lisp</li>' + '<li>Templating: Djula (prepared)</li>' + '<li>Server: Node.js</li></ul>' + '<a href=\'/\'>← Back to Home</a>' + '</div></body></html>';
    __PS_MV_REG = [];
    return sendHtml(res, html);
};
function handleApiStats(req, res) {
    var jsonResponse = '{\"visitor-count\":' + VISITORCOUNT + ',\"uptime\":' + process.uptime() + ',\"server\":\"Parenscript Dynamic Server\"}';
    __PS_MV_REG = [];
    return sendJson(res, jsonResponse);
};
function handleRequest(req, res) {
    var pathname = URL.parse(req.url, true)['pathname'];
    if (pathname === '/') {
        __PS_MV_REG = [];
        return handleRoot(req, res);
    } else if (pathname.length > 6 && pathname.substring(0, 6) === '/user/') {
        var username = pathname.substring(6);
        __PS_MV_REG = [];
        return handleUser(req, res, username);
    } else if (pathname.length > 6 && pathname.substring(0, 6) === '/post/') {
        var postId = pathname.substring(6);
        __PS_MV_REG = [];
        return handlePost(req, res, postId);
    } else if (pathname === '/api/stats') {
        __PS_MV_REG = [];
        return handleApiStats(req, res);
    } else {
        __PS_MV_REG = [];
        return sendError(res, 404, 'Not Found');
    };
};
function startServer() {
    var server = HTTP.createServer(handleRequest);
    server.listen(PORT, function () {
        console.log('🚀 Dynamic Server running on port ' + PORT);
        console.log('Try: http://localhost:' + PORT + '/user/alice');
        __PS_MV_REG = [];
        return console.log('Try: http://localhost:' + PORT + '/post/123');
    });
    __PS_MV_REG = [];
    return server;
};
startServer();