if ('undefined' === typeof HTTP) {
    var HTTP = require('http');
};
if ('undefined' === typeof URL) {
    var URL = require('url');
};
if ('undefined' === typeof PORT) {
    var PORT = 3000;
};
if ('undefined' === typeof VISITORCOUNT) {
    var VISITORCOUNT = 0;
};
if ('undefined' === typeof HOMETEMPLATE) {
    var HOMETEMPLATE = '<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Dynamic Server</title>\n    <style>\n        body {\n            font-family: Arial, sans-serif;\n            margin: 40px;\n            background: #f0f8ff;\n        }\n        .container {\n            max-width: 800px;\n            margin: 0 auto;\n            background: white;\n            padding: 30px;\n            border-radius: 15px;\n            box-shadow: 0 4px 15px rgba(0,0,0,0.1);\n        }\n        .route {\n            background: #e8f4fd;\n            padding: 15px;\n            margin: 10px 0;\n            border-radius: 8px;\n            border-left: 5px solid #3498db;\n        }\n        a {\n            color: #3498db;\n            text-decoration: none;\n            font-weight: bold;\n        }\n        a:hover {\n            text-decoration: underline;\n        }\n        .avatar {\n            width: 80px;\n            height: 80px;\n            border-radius: 50%;\n            background: #3498db;\n            color: white;\n            display: flex;\n            align-items: center;\n            justify-content: center;\n            font-size: 32px;\n            margin: 0 auto 20px;\n        }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        \n<h1>🚀 Dynamic Parenscript Server</h1>\n<p>Visitor count: {{visitor_count}}</p>\n\n<h2>Dynamic Routes:</h2>\n<div class=\"route\">\n    <a href=\"/user/alice\">👤 /user/alice</a> - User profile\n</div>\n<div class=\"route\">\n    <a href=\"/user/bob\">👤 /user/bob</a> - Another user\n</div>\n<div class=\"route\">\n    <a href=\"/post/123\">📝 /post/123</a> - Blog post\n</div>\n<div class=\"route\">\n    <a href=\"/post/456\">📝 /post/456</a> - Another post\n</div>\n<div class=\"route\">\n    <a href=\"/api/stats\">📊 /api/stats</a> - Server statistics\n</div>\n\n    </div>\n</body>\n</html>\n';
};
if ('undefined' === typeof USERTEMPLATE) {
    var USERTEMPLATE = '<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>User: {{username}}</title>\n    <style>\n        body {\n            font-family: Arial, sans-serif;\n            margin: 40px;\n            background: #f0f8ff;\n        }\n        .container {\n            max-width: 800px;\n            margin: 0 auto;\n            background: white;\n            padding: 30px;\n            border-radius: 15px;\n            box-shadow: 0 4px 15px rgba(0,0,0,0.1);\n        }\n        .route {\n            background: #e8f4fd;\n            padding: 15px;\n            margin: 10px 0;\n            border-radius: 8px;\n            border-left: 5px solid #3498db;\n        }\n        a {\n            color: #3498db;\n            text-decoration: none;\n            font-weight: bold;\n        }\n        a:hover {\n            text-decoration: underline;\n        }\n        .avatar {\n            width: 80px;\n            height: 80px;\n            border-radius: 50%;\n            background: #3498db;\n            color: white;\n            display: flex;\n            align-items: center;\n            justify-content: center;\n            font-size: 32px;\n            margin: 0 auto 20px;\n        }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        \n<div class=\"avatar\">{</div>\n<h1>👤 User Profile: {{username}}</h1>\n<p>Welcome, {{username}}!</p>\n<p>This is a dynamic route generated by Parenscript with Djula templating.</p>\n<a href=\"/\">← Back to Home</a>\n\n    </div>\n</body>\n</html>\n';
};
if ('undefined' === typeof POSTTEMPLATE) {
    var POSTTEMPLATE = '<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Post #{{post_id}}</title>\n    <style>\n        body {\n            font-family: Arial, sans-serif;\n            margin: 40px;\n            background: #f0f8ff;\n        }\n        .container {\n            max-width: 800px;\n            margin: 0 auto;\n            background: white;\n            padding: 30px;\n            border-radius: 15px;\n            box-shadow: 0 4px 15px rgba(0,0,0,0.1);\n        }\n        .route {\n            background: #e8f4fd;\n            padding: 15px;\n            margin: 10px 0;\n            border-radius: 8px;\n            border-left: 5px solid #3498db;\n        }\n        a {\n            color: #3498db;\n            text-decoration: none;\n            font-weight: bold;\n        }\n        a:hover {\n            text-decoration: underline;\n        }\n        .avatar {\n            width: 80px;\n            height: 80px;\n            border-radius: 50%;\n            background: #3498db;\n            color: white;\n            display: flex;\n            align-items: center;\n            justify-content: center;\n            font-size: 32px;\n            margin: 0 auto 20px;\n        }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        \n<h1>📝 Blog Post #{{post_id}}</h1>\n<p>This is post number {{post_id}}.</p>\n<p>Generated dynamically by Parenscript with Djula templating!</p>\n\n<h3>Technical Details:</h3>\n<ul>\n    <li>Route: <code>/post/{{post_id}}</code></li>\n    <li>Generated by: Parenscript from Common Lisp</li>\n    <li>Templating: Djula</li>\n    <li>Server: Node.js</li>\n</ul>\n<a href=\"/\">← Back to Home</a>\n\n    </div>\n</body>\n</html>\n';
};
function sendHtml(res, html) {
    res.statusCode = 200;
    res['content-type'] = 'text/html';
    __PS_MV_REG = [];
    return res.end(html);
};
function sendJson(res, jsonString) {
    res.statusCode = 200;
    res['content-type'] = 'application/json';
    __PS_MV_REG = [];
    return res.end(jsonString);
};
function substituteTemplate(template, placeholder, value) {
    var parts = template.split(placeholder);
    return parts.join(value);
};
function sendError(res, status, message) {
    res.statusCode = status;
    res['content-type'] = 'text/plain';
    __PS_MV_REG = [];
    return res.end(message);
};
function handleRoot(req, res) {
    VISITORCOUNT += 1;
    var html = substituteTemplate(HOMETEMPLATE, '{{visitor_count}}', '' + VISITORCOUNT);
    __PS_MV_REG = [];
    return sendHtml(res, html);
};
function handleUser(req, res, username) {
    var html = substituteTemplate(USERTEMPLATE, '{{username}}', username);
    __PS_MV_REG = [];
    return sendHtml(res, html);
};
function handlePost(req, res, postId) {
    var html = substituteTemplate(POSTTEMPLATE, '{{post_id}}', postId);
    __PS_MV_REG = [];
    return sendHtml(res, html);
};
function handleApiStats(req, res) {
    var jsonResponse = '{\"visitor-count\":' + VISITORCOUNT + ',\"uptime\":' + process.uptime() + ',\"server\":\"Parenscript Dynamic Server\"}';
    __PS_MV_REG = [];
    return sendJson(res, jsonResponse);
};
function handleRequest(req, res) {
    var pathname = URL.parse(req.url, true)['pathname'];
    if (pathname === '/') {
        __PS_MV_REG = [];
        return handleRoot(req, res);
    } else if (pathname.length > 6 && pathname.substring(0, 6) === '/user/') {
        var username = pathname.substring(6);
        __PS_MV_REG = [];
        return handleUser(req, res, username);
    } else if (pathname.length > 6 && pathname.substring(0, 6) === '/post/') {
        var postId = pathname.substring(6);
        __PS_MV_REG = [];
        return handlePost(req, res, postId);
    } else if (pathname === '/api/stats') {
        __PS_MV_REG = [];
        return handleApiStats(req, res);
    } else {
        __PS_MV_REG = [];
        return sendError(res, 404, 'Not Found');
    };
};
function startServer() {
    var server = HTTP.createServer(handleRequest);
    server.listen(PORT, function () {
        console.log('🚀 Dynamic Server running on port ' + PORT);
        console.log('Try: http://localhost:' + PORT + '/user/alice');
        __PS_MV_REG = [];
        return console.log('Try: http://localhost:' + PORT + '/post/123');
    });
    __PS_MV_REG = [];
    return server;
};
startServer();