name = "parenscript-worker"
main = "worker.js"
compatibility_date = "2024-10-01"

[durable_objects]
bindings = [
  { name = "USER_DO", class_name = "UserDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["UserDO"]

name = "parenscript-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# Serve static assets
[assets]
directory = "assets"
binding = "ASSETS"

[env.production]
name = "parenscript-worker"

[env.staging]
name = "parenscript-worker-staging"
